### PR TITLE
Build Module Stable and support RxSwift 6

### PR DESCRIPTION
**Pull request by ghost**
Build with Module stability AND update to RxSwift 6

### CODE REVIEW

**Comment by janrose-lca** [comment]
@rsobik @PaulEhrhardt 

I'd like to create a 1.4 Release after this is merged

**Review by PaulEhrhardt — CHANGES_REQUESTED** [review]
Cocoapods is not reflected by this upgrade. I propose you add the new `1.4.0` version to the Pods trunk too.
Alternatively one can also consider to drop Cocoapods but i would prefer the first.

**Comment by janrose-lca** [comment]
@PaulEhrhardt I'm not that experienced with Cocoapods. Hope I did it the right way

**Comment by PaulEhrhardt** [comment]
@janrose-gcx That's correct, the last missing step is to upload the podspec to cocoapods via trunk. 
https://guides.cocoapods.org/making/getting-setup-with-trunk.html
I added your gcx email as repo owner to trunk. You can now open a session by typing:
```
pod trunk register YOUR_GCX_EMAIL 'RxGCXMulticastDNSKit' --description='my device used in that session'
```

**Comment by janrose-lca** [comment]
@PaulEhrhardt 
I would have to do that before or after this is merged and released as 1.4?

**Comment by PaulEhrhardt** [comment]
@PaulEhrhardt I always did it upfront to not have to re-release again if something was missing e.g. in the spec file or the validation failed. But it is also ok to do it afterwards if you are confident all will go well.

**Review by PaulEhrhardt — APPROVED** [review]
LGTM

**Comment by janrose-lca** [comment]
Merged, created a new release and published to Cocoapods

**Pull request merged**
